"""add foreign key to Review

Revision ID: 0d1c8ac23fb0
Revises: 2909b1ea23a5
Create Date: 2025-06-15 21:36:19.756702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1c8ac23fb0'
down_revision = '2909b1ea23a5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - modified for SQLite batch mode ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f('fk_reviews_employee_id_employees'),
            'employees',
            ['employee_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - modified for SQLite batch mode ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_reviews_employee_id_employees'),
            type_='foreignkey'
        )
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
